 
 /*------------------------------------------------------------------------
    File        : Customer
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : nvasilev
    Created     : Wed Apr 22 11:13:57 EEST 2020
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS Entities.Customer: 

END CLASS.